### PR TITLE
Exciter ``ESST1A``

### PR DESCRIPTION
**Pull request by jinningwang**
Developed ``ESST1A``.

### CODE REVIEW

**Comment by jinningwang** [comment]
Woohoo, all checks passed!

**Comment by cuihantao** [comment]
I added a "ready to merge" label. It can be added in the right column at the top. You can set the label when ready. Thanks!!

**Comment by jinningwang** [comment]
All checks passed, this PR is ready to merge.

**Comment by cuihantao** [comment]
Thanks!!

**Pull request merged**
