### PR TITLE
Dynamic Model #1 Revision

### PR DESCRIPTION
**Pull request by jinningwang**
Revised the recently developed ``AC8B`` and ``PID`` related blocks.

1) Revised ``AC8B``:  use ``PIDTrackAW`` rather than ``PIDAWHardLimit``.
2) Refactored ``PIDController`` and ``PIDAWHardLimit``.
3) Derived ``PIDTrackAW`` from ``PITrackAW``.

### CODE REVIEW

**Comment by cuihantao** [comment]
There's an error in the docstring:
```
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/andes/core/block.py:docstring of andes.core.block.PIDController:15:Inline literal start-string without end-string.
```

**Comment by cuihantao** [comment]
It is in this line:

`This block assembles a ``PIController``(PIC) and a ``Washout``(WO).`

There needs to be a space between `` and the left parenthesis for both.

**Comment by jinningwang** [comment]
> It is in this line:
> 
> `` This block assembles a ``PIController``(PIC) and a ``Washout``(WO). ``
> 
> There needs to be a space between `` and the left parenthesis for both.

I've taken care of them.
May I ask how you find the error source? I don't find that from CodeRev.

**Comment by jinningwang** [comment]
> Sure. You can click on the "Details" to the right of the Azure pipeline, in the checking block above (or below). At the bottom of the new page, find "View more details on Azure Pipelines", and open it. Click on the jobs with an error mark to view the details.
> 
> For example, the error was found on this page: https://dev.azure.com/hcui7/hcui7/_build/results?buildId=1817&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=244
> 
> Edit: this check was to ensure that documentation will build.

Thanks for your reply.

It looks like we may need more tests for those newly developed blocks. Will you take care or we can ignore that for time being?

**Comment by cuihantao** [comment]
It’s difficult to test the blocks individually. We should ensure they are implemented correctly by double checking. Then we can move on.

Regards,
Hantao Cui

**Comment by jinningwang** [comment]
> It’s difficult to test the blocks individually. We should ensure they are implemented correctly by double checking. Then we can move on. Regards, Hantao Cui

I have tested those ``PID`` blocks when testing ``AC8B``,  so I think we are good to go.

Regards,
Jinning

**Pull request merged**
