### PR TITLE
Dynamic Model (Exciter) Development

### PR DESCRIPTION
**Pull request by jinningwang**
# Dynamic Model Development

09/22/2022, 2
Prepared: AC8B, IEEET3
Undergoing: ESAC1A, ESST1A, GAST, IEEEVC

1) Developed: AC8B
2) Developed blocks ``PIDController`` and ``PIDAWHardLimiter``.
3) Revised block ``Lag`` and its related block. Now the constant in denominator ``1`` is replaced with ``D``.
4) Developed: IEEET3

***

09/22/2022
Prepared: AC8B
Undergoing: IEEET3, ESAC1A, ESST1A, GAST, IEEEVC

1) Developed: AC8B
2) Developed blocks ``PIDController`` and ``PIDAWHardLimiter``.
3) Revised block ``Lag`` and its related block. Now the constant in denominator ``1`` is replaced with ``D``.

Trouble: In ``IEEET3``, ``VTHEV`` cannot pass ``andes prep``. There is trouble with complex v_str. (3531f1c)
Solved: it turned out to be I missed four necessary variables. Now ``IEEET3`` can pass ``andes prep``. Initialization needs to be tested. (3108932)

TODO: Docstring for ``PIDController`` and ``PIDAWHardLimiter`` may need enhance.

### CODE REVIEW

**Comment by jinningwang** [comment]
# AC8B Prepared

1) Prepared model `AC8B`.
2) Added an example file and a demo for`AC8B`.

**Comment by cuihantao** [comment]
> # AC8B Prepared 
> 
> 
> 
> 1) Prepared model `AC8B`.
> 
> 2) Added an example file and a demo for `AC8B`.

Thanks. The title of the AC8B notebook needs updating.

**Comment by jinningwang** [comment]
> > # AC8B Prepared
> > 
> > 1. Prepared model `AC8B`.
> > 2. Added an example file and a demo for `AC8B`.
> 
> Thanks. The title of the AC8B notebook needs updating.

Sure, what name style would be appropriate? My plan is '2.x demo_modelname.ipynb', but this can be insufficient.

**Comment by cuihantao** [comment]
That’s fines. But I mean the title inside the notebook, not the file name.

**Comment by jinningwang** [comment]
> That’s fines. But I mean the title inside the notebook, not the file name.
> […](#)

Okay, I've taken care of it.

**Comment by jinningwang** [comment]
# IEEET3 Prepared
1) Prepared model ``IEEET3``.
2) Added an example file and a demo for ``IEEET3``.

**Comment by jinningwang** [comment]
@cuihantao 
Hi Hantao,

I'm curious how you create the ASCII diagram?
Maybe it is better to have such a diagram for the ``PID`` block:
image

Regards,
Jinning

**Comment by cuihantao** [comment]
It was hand crafted. Feel free to use the elements from existing ones.  Sent from Mail for Windows From: Jinning WangSent: Wednesday, September 22, 2021 1:04 PMTo: cuihantao/andesCc: Hantao Cui; MentionSubject: Re: [cuihantao/andes] Dynamic Model (Exciter) Development ***@***.*** Hantao,I'm curious how you create the ASCII diagram?Maybe it is better to have such a diagram for the PID block:Regards,Jinning—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
