### PR TITLE
Prepare for v1.4.3 release

### PR DESCRIPTION
**Pull request by cuihantao**

### CODE REVIEW

**Comment by cuihantao** [comment]
@jinningwang Could you fix the "Code Smells" as listed by sonarcloud above? Basically, you will need to remove the unused, comment out code. 

I will release a new version once fixed.

**Comment by jinningwang** [comment]
> @jinningwang Could you fix the "Code Smells" as listed by sonarcloud above? Basically, you will need to remove the unused, comment out code.
> 
> I will release a new version once fixed.

Sure, I will do it now.

**Comment by jinningwang** [comment]
It seems that the duplication issue occurs again, I will try to refactor recently developed models.

**Comment by cuihantao** [comment]
@jinningwang Let's not worry about the duplication issues in exciters for now. There are indeed lots of shared, i.e., common blocks, such as the piecewise saturation. We can fix it later.

**Comment by jinningwang** [comment]
> @jinningwang Let's not worry about the duplication issues in exciters for now. There are indeed lots of shared, i.e., common blocks, such as the piecewise saturation. We can fix it later.

Oh, I have refactored part of the AC8B and ESAC1A.
So, do we need to pay attention to the duplication rates?

**Comment by cuihantao** [comment]
We of course need to pay attention to it, but the solution depends. 

 

It would be helpful if you could fix them now. The duplications in the exciter models are due to the similarity between the models, so it’s containable. Copying and pasting code for the same feature is less acceptable.

**Pull request merged**
