### PR TITLE
Gridcal interface

### PR DESCRIPTION
**Pull request by JosepFanals**
Hello,

I have written an interface that allows going from a system defined in Andes to a GridCal system. The power flow results for the cases found in the created `test_gridcal.py` coincide. Please let me know if there is any improvement to be made.

With gratitude,

Josep Fanals

### CODE REVIEW

**Comment by cuihantao** [comment]
Hi Josep,

Thanks for the pull request! You may go ahead and remove some unnecessary files/folders, such as `andes/bin`, `lib64`, `pyvenc.cfg` and `share`. There are some style suggestions from SonarCloud above. You may decide to follow them or not.

I will take a look next.

**Comment by JosepFanals** [comment]
Hi @cuihantao,

Thank you for your comments. The files/directories you suggested are now removed. I have also payed attention to the SonarCloud naming suggestions.

**Comment by cuihantao** [comment]
Thank you! It looks like the macOS test failed due to the import of the plotting library. I'm not sure if that's transitory or not. Launching a new CI run for now.

**Comment by cuihantao** [comment]
It looks like GridCal's GUI sets the backend `Qt5Agg` here: https://github.com/SanPen/GridCal/blob/master/src/GridCal/Gui/plot_config.py. A display environment is not always available.

Is there a way not to import GridCal's GUI?

**Comment by JosepFanals** [comment]
Hi, it is enough to import `GridCal.Engine` and thus avoid importing the whole `GridCal` with the GUI. The macos test for python 3.8 is successful.

**Comment by cuihantao** [comment]
Thank you, @JosepFanals. The PR looks great. I will get it merged in a moment.

**Pull request merged**
