### PR TITLE
Model `DGPRCT` (Previously named `PLK2`)

### PR DESCRIPTION
**Pull request by jinningwang**
This is an early version of PLK2.
The multi-level frequency and voltage tripping points are added.
The improvements of the model remain to be finished.

### CODE REVIEW

**Comment by cuihantao** [comment]
What's next for this PR? @jinningwang

**Comment by jinningwang** [comment]
> What's next for this PR? @jinningwang

Oh, I plan to give an early version PLK2. It can lock the ``f``, ``Psum``, and ``Qsum`` (these three are ``Algebs``).
Accordingly, ``Qsum`` of PVD1 is separated into two parts.

**Comment by jinningwang** [comment]
An early version PLK2.

It can lock the ``f``, ``Psum``, and ``Qsum`` (these three are ``Algeb``s).
Accordingly, ``Qsum`` in `PVD1` is separated into two ``Algeb``s.
Also, redundant variables ``Pe`` and ``Qe`` in `PVD1` are removed for efficiency.

# TODO: clear ``State`` when lock flag is raised.

**Comment by cuihantao** [comment]
Sounds good. You can leave it open and keep pushing to the branch. Let me know if it's feature ready.

**Comment by jinningwang** [comment]
> Sounds good. You can leave it open and keep pushing to the branch. Let me know if it's feature ready.

Sure, thanks for your guidance.

Also, since the `PVD1` is not good written, maybe we can discard it in the future? (Like EV2 and EV1 can be combined as EV1).

**Comment by cuihantao** [comment]
We can mark it as deprecated in the future to allow time for transition. Since it’s not widely used, it can be removed after a couple of releases.

Regards,
Hantao Cui

**Comment by jinningwang** [comment]
> We can mark it as deprecated in the future to allow time for transition. Since it’s not widely used, it can be removed after a couple of releases. Regards, Hantao Cui
> […](#)

Got it, thanks!

Regards,
Jinning

**Comment by cuihantao** [comment]
@jinningwang 

Thanks. It was working in REECA1 in my last testing, but it was a year ago.

**Comment by jinningwang** [comment]
## Ready-to-use version ##

The model is considered ready-to-use.

* The reset function is realized through `IntegratorAntiWindup`. Now the integrator will go back to zero after the protection is finished./n
Accordingly, `AntiWindup` and `IntegratorAntiwindup` is added a parameter `no_warn = False`. In the `DGPRCT`, `IAW` `no_warn` is set at `True` to reduce the TDS output.
* `State` behind `Ipout` and `Iqout` in `PVD1` will not be reset by force since it is reasonable to let them go down and go up with a lag.
* Frequency signal is designed to be left online in the protection so that the device can be aware of the protection complete.

**Comment by cuihantao** [comment]
Thanks for taking care of the `no_warn` argument for `AntiWindup`.

**Comment by cuihantao** [comment]
@jinningwang Would you like to include the test case files?

**Review by cuihantao — APPROVED** [review]

**Comment by jinningwang** [comment]
> @jinningwang Would you like to include the test case files?

Added input files and demonstration notebook.

Hope it helps.

Regards,
Jinning

**Comment by jinningwang** [comment]
@cuihantao 
Hi Hantao,

I added a notebook file for `DGPRCTExt`, shall we reopen this to merge them?

Regards,
Jinning

**Comment by cuihantao** [comment]
You can make a new PR.

Regards,
Hantao Cui

**Review by cuihantao — APPROVED** [review]

**Review by cuihantao — APPROVED** [review]

**Pull request merged**
