### PR TITLE
Fix PSSE parser of WTDTA1

### PR DESCRIPTION
**Pull request by jinningwang**
- Fix equations of WTDTA1
- Fix WTDTA1 in PSSE parser
- Add `non_negative=True` to the param `Mass` in GENBASE, WTDTA1, WTDS

### CODE REVIEW

**Comment by jinningwang** [comment]
Hantao,

I compared the PowerWorld WTDTA1 and our implementation of WTDTA1, and I think that the equation of WTDTA1 in the PSSE parser should be modified.
image
Do I miss anything else?

Regards,
Jinning

**Comment by cuihantao** [comment]
Thanks for the PR! 

Can you modify the PSSE parser to allow the use of a variable, sys_f, in any equation? This seems to be a much needed feature.

**Comment by cuihantao** [comment]
I made a mistake in the original equation by forgetting about the square. Can you analyze the control diagram and figure out if Freq1 need to be converted to per unit? Recall that in WTDTA1 in ANDES, all other quantities such as H, D, omega are in per unit in system base. The unit of Freq1 should be consistent for the swing equations.

**Comment by jinningwang** [comment]
> Thanks for the PR!
> 
> Can you modify the PSSE parser to allow the use of a variable, sys_f, in any equation? This seems to be a much needed feature.

Sure thing, let me try some solutions.

**Comment by jinningwang** [comment]
> I made a mistake in the original equation by forgetting about the square. Can you analyze the control diagram and figure out if Freq1 need to be converted to per unit? Recall that in WTDTA1 in ANDES, all other quantities such as H, D, omega are in per unit in system base. The unit of Freq1 should be consistent for the swing equations.

I'll check this.

**Comment by jinningwang** [comment]
> 

Hantao, although PSSE doc said it is nominal frequency, I think per unit is more reasonable. In the test dyr file, the variable is given in per unit.
image

Regards,
Jinning

**Comment by cuihantao** [comment]
> Hantao, although PSSE doc said it is nominal frequency, I think per unit is more reasonable. In the test dyr file, the variable is given in per unit.
Something might be wrong here. Either the doc or PSS/E's not following the doc.

Anyway, what I asked you to do is to perform a rigorous analysis of the swing equation to *reason* if `Freq1` needs to be in per unit or Hz. The manual is a reference, but an analysis is needed.

**Comment by jinningwang** [comment]
> > Hantao, although PSSE doc said it is nominal frequency, I think per unit is more reasonable. In the test dyr file, the variable is given in per unit.
> 
> Something might be wrong here. Either the doc or PSS/E's not following the doc.
> 
> Anyway, what I asked you to do is to perform a rigorous analysis of the swing equation to _reason_ if `Freq1` needs to be in per unit or Hz. The manual is a reference, but an analysis is needed.

Sure, let me do this after fixing the initialization error of WTDTA1.

**Comment by jinningwang** [comment]
Hantao,

I think this PR is ready to merge, all the issues related to WTDTA1 are solved:
- The `Freq1` should be in per unit after I analyze the equations, I add notices in the docstring of WTDTA1;
- The initialization error is fixed when `Kshaft=0`.

The enhancement of adding `sys_f` in the PSSE parser can be done in another PR.

Regards,
Jinning

**Review by cuihantao — APPROVED** [review]
Looks good.

**Pull request merged**
